- id: '1710004236293'
  alias: awtrix_mega_weather
  description: from HA community awtrix mega weather
  use_blueprint:
    path: jeeftor/awtrix_weatherflow.yaml
    input:
      awtrix:
      - a8583420298728779e89f960f8079d14
      forecast_var: weather.forecast_home
      forecast_temp_field: temperature
      temp_suffix: °
      current_temp_var: sensor.kflwildw56_local_temperature
      moon: sensor.moon_phase
      moon_rise_set: sensor.ip_geo_location
      show_sun_rise_set: false
      message_duration_riseset: 0
      message_duration_forecast: 10
      hours_to_show: 12
      temp_digits: 0
