# Configure a default setup of Home Assistant (frontend, api, etc)

homeassistant:
  name: Norcoose # Name where Home Assistant is running
  latitude: !secret latitude # Location for sun rises and set calc
  longitude: !secret longitude
  elevation: 23 # (meters) needed for weather/sunrise functions
  unit_system: imperial # 'metric' for Metric, 'imperial' for Imperial
  currency: USD
  time_zone: America/New_York # google "List of TZ database time zones"
  external_url: !secret external_url
  internal_url: !secret internal_url
  allowlist_external_dirs:
    - /config # this is required for filesize sensor to work on the home assistant db
  customize: !include customize.yaml # customize, customize_domain, & customize_glob
  customize_domain: !include customize_domain.yaml # must be under the homeassistant: section
  customize_glob: !include customize_glob.yaml # or it will not work

http:
  # server_port: 61615                                 #  default port 8123 is used for local network unencrypted http
  #  ssl_certificate: /ssl/fullchain.pem               #  WAN port 443 must pass thru to 443 on HA for cert renewal
  #  ssl_key: /ssl/privkey.pem                         #  ssl keys are renewed by DuckDNS or nginx (not sure which)
  use_x_forwarded_for: true # required for
  trusted_proxies: # reverse proxy
    - 10.0.0.44 #   home assistant address
    - 172.0.0.0/8 #   internal network for docker

default_config:

#stream: # Enables stream component
#ffmpeg: # enables ffmpeg integration

frontend: # Enables the frontend
  themes: !include_dir_merge_named themes # themes go in the themes directory

# NEATO VACUUM
neato:
  client_id: !secret neato_client_id
  client_secret: !secret neato_client_secret

# GOOGLE CALENDAR
google:
  client_id: !secret google_cal_client_id
  client_secret: !secret google_cal_client_secret

# OTHER HA HUBS
vera:
  #  vera_controller_url: http://veraplus.shencentral.net:3480/
  vera_controller_url: http://10.0.0.40:3480/

############################################
# INCLUDES
############################################

# note the include for customize: is required
# to be in the homeassitant: section

history: !include history.yaml # doesn't work, check all three
logger: !include logger.yaml
influxdb: !include influxdb.yaml
recorder: !include recorder.yaml # history graphing settings
group: !include groups.yaml
automation: !include automations.yaml # hassio generated yaml goes here
automation old: !include_dir_merge_list automations # hand coded yaml goes in this dir
sensor: !include sensors.yaml
script: !include scripts.yaml
tts: !include tts.yaml
#device_tracker: !include device_trackers.yaml
binary_sensor: !include binary_sensors.yaml
input_boolean: !include input_booleans.yaml
input_select: !include input_selects.yaml
#input_text: !include input_text.yaml
input_number: !include input_numbers.yaml
light: !include lights.yaml
switch: !include switches.yaml
cover: !include covers.yaml
media_player: !include media_players.yaml
scene: !include scenes.yaml
notify: !include notifiers.yaml
#alert: !include alerts.yaml
camera: !include cameras.yaml
proximity: !include proximity.yaml
shell_command: !include shell_commands.yaml
#climate: !include climate.yaml
alexa: !include alexa.yaml
zone: !include zones.yaml
