##  Note: leading spaces in each line are critical
##  to yaml interpretation - do not delete them

### COVERS  ###

# Note some covers are interfaced via Vera
# and are not configured here also
# MQTT covers are configured in mqtt.yaml

- platform: group
  name: "Sun Room Shades"
  entities:
    - cover.sun_room_shade_1
    - cover.sun_room_shade_2
    - cover.sun_room_shade_3
    - cover.sun_room_shade_4

- platform: group
  name: "Garage Doors"
  entities:
    - cover.large_garage_door
    - cover.small_garage_door
