
##  Note: leading spaces in each line are critical
##  to yaml interpretation - do not delete them


### COVERS  ###

# Note some covers are interfaced via Vera
# and are not configured here

- platform: group
  name: "Sun Room Shades"
  entities:
    - cover.sun_room_shade_1
    - cover.sun_room_shade_2
    - cover.sun_room_shade_3
    - cover.sun_room_shade_4

- platform: group
  name: "Garage Doors"
  entities:
    - cover.large_garage_door
    - cover.small_garage_door

# MQTT #
## Large Garage Door ##
- platform: mqtt
  name: "Large Garage Door"
  state_topic: "garage/LgGarDoor/zeroisclosed"
  state_open: "1"
  state_closed: "0"
  command_topic: "garage/cmd"
  payload_open: "pulse,4,1,500"
  payload_close: "pulse,4,1,500"
  qos: 0

## Small Garage Door ##
- platform: mqtt
  name: "Small Garage Door"
  state_topic: "garage/SmGarDoor/zeroisclosed"
  state_open: "1"
  state_closed: "0"
  command_topic: "garage/cmd"
  payload_open: "pulse,5,1,500"
  payload_close: "pulse,5,1,500"
  qos: 0

