
##  Note: leading spaces in each line are critical
##  to yaml interpretation - do not delete them


### DEVICE TRACKERS  ###

# Note: OwnTracks and Life360 configuration is no longer configured here
#       They have been moved to the configuration.yaml file

- platform: netgear
  username: !secret netgear_user
  password: !secret netgear_pwd
  host: !secret netgear_host
  port: 80
  consider_home: 180                   # allow for occassional drop offs in seconds
  devices:
  - ys-cell
  - kt-cell
  
