##  Note: leading spaces in each line are critical
##  to yaml interpretation - do not delete them
 
############# 
## FILTERS ##
############# 

- platform: filter
  name: "Filtered Solar Tube Luminosity" 
  entity_id: sensor.raw_solar_tube_luminosity
  filters:
    - filter: lowpass                       # lowpass is exponential smoothing
      time_constant: 10                     # 10 is the default value
