##  Note: leading spaces in each line are critical
##  to yaml interpretation - do not delete them
 
############## 
## SWITCHES ##
############## 

##  Can't find a switch?
##  Some MQTT switches are sutomatically added 
##  via auto discovery and are not listed below


- platform: mqtt
  name: "Water Valve"
  unique_id: water_valve
  state_topic: "watermain/zeroisclosed"
  command_topic: "watermain/cmd/valveState"
  payload_on: "1"
  payload_off: "0"
  qos: 2
  