esphome:
  name: dot-matrix-clock-1
  friendly_name: dot-matrix-clock-1

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XASMcaNySrTUFMSCdqA6hEb3Dc7Wz6zecQ8uqY0YRMU="

ota:
  password: "cbb101b02a504f1237b5dc67dd385cb5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}

captive_portal:

spi:
  clk_pin: D5
  mosi_pin: D7

time:
  - platform: sntp
    id: internet_time

display:
  - platform: max7219digit
    cs_pin: D6
    num_chips: 4
    intensity: 2
    lambda: |-
      it.strftime(6, 0, id(default_font), "%I:%M", id(internet_time).now());

# A good source for 8x8 fonts: https://damieng.com/typography/zx-origins/      
font: 
  - file: fonts/bright_lights_.ttf
    id: default_font
    glyphs:  |
      ! "#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz°
    size: 8

# image:
#   - file: "images/smile.png"
#     id: my_image