substitutions:
  name: esp32-s3-box-3-05adcc
  friendly_name: voice-assistant-office
packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: FVmitbC/1heZEvd9dRcGBuPH7fLLQOgRBtWXJPHTvbo=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
