substitutions:
  name: esp32-s3-box-3-05adcc
  friendly_name: ESP32 S3 Box 3 05adcc
packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
#  encryption:
#    key: KRzP/AR5w+AMXGAAMiN6rsKo5pQdBQB5A2PJKBfCKx4=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".shencentral.net"

