esphome:
  name: garage-control
  friendly_name: garage-control
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".shencentral.net"
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}

captive_portal:
