esphome:
  name: garage-controller
  friendly_name: garage-controller
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: mhetesp32minikit
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".shencentral.net"

  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}

captive_portal:

#
# DEFINE GPIOs
#
binary_sensor:
  - platform: gpio
    name: "Lg Garage is Closed"
    id: lg_garage_is_closed
    device_class: garage_door
    pin:
      number: GPIO27             # blue wire
      inverted: true
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: "Lg Garage is Open"
    id: lg_garage_is_open
    device_class: garage_door
    pin:
      number: GPIO25             # brown wire
      inverted: true
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: "Sm Garage is Closed"
    id: sm_garage_is_closed
    device_class: garage_door
    pin:
      number: GPIO32              # violet wire
      inverted: true
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: "Sm Garage is Open"
    id: sm_garage_is_open
    device_class: garage_door
    pin:
      number: GPIO12               # yellow wire
      inverted: true
      mode:
        input: true
        pullup: true

switch:
- platform: gpio
  name: "Lg Garage Trigger"
  id: lg_garage_trigger
  pin:
    number: GPIO16                  # orange wire
- platform: gpio
  name: "Sm Garage Trigger"
  id: sm_garage_trigger
  pin:
    number: GPIO17

one_wire:
  - platform: gpio                  # green wire
    pin: GPIO13

#
# EXPOSE SENSORS/ENTITIES
#
sensor:
  # Send WiFi signal strength & uptime to HA
  - platform: wifi_signal
    name: Garage Controller WiFi Strength
    id: garage_control_wifi_strength
    unit_of_measurement: 'dBm'
    update_interval: 60s

  - platform: dallas_temp
    name: "Garage Controller Temperature"
    id: garage_controller_temperature
    update_interval: 60s
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1


cover:
  - platform: feedback
    name: "Large Garage"

    open_action:
      - switch.turn_on: lg_garage_trigger
    open_duration: 16.5s
    open_endstop: lg_garage_is_open

    close_action:
      - switch.turn_on: lg_garage_trigger
    close_duration: 16.5s
    close_endstop: lg_garage_is_closed

    stop_action:
      - switch.turn_off: lg_garage_trigger
      - switch.turn_off: lg_garage_trigger

  - platform: feedback
    name: "Small Garage"
    open_action:
      - switch.turn_on: sm_garage_trigger
    open_duration: 15s
    open_endstop: sm_garage_is_open

    close_action:
      - switch.turn_on: sm_garage_trigger
    close_duration: 15s
    close_endstop: sm_garage_is_closed

    stop_action:
      - switch.turn_off: sm_garage_trigger
      - switch.turn_off: sm_garage_trigger