substitutions:
  name: office-speakers
  friendly_name: "office-speakers"

esphome:
  name: "${name}"
  # Friendly names are used where appropriate in Home Assistant
  friendly_name: "${friendly_name}"

esp32:
  board: mhetesp32minikit
  framework:
    type: esp-idf
    version: recommended
    # version: 4.4.8
    # platform_version: 5.4.0

# Enable logging if desired
logger:
  # level: DEBUG

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain   # remove this line if you don't use domain names

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}

captive_portal:

i2s_audio:
  i2s_lrclk_pin: GPIO33
  i2s_bclk_pin: GPIO19

speaker:
  - platform: i2s_audio
    id: output_speaker
    i2s_dout_pin: GPIO22
    dac_type: external    
    bits_per_sample: 32bit
    channel: mono
    buffer_duration: 60ms

media_player:
  - platform: speaker
    name: ${friendly_name}
    id: media_out
    announcement_pipeline:
      speaker: output_speaker
      format: WAV
    codec_support_enabled: false
    buffer_size: 8000
    on_pause:
      - logger.log: "Playback paused!"
    on_idle:
      - logger.log: "Playback finished!"    

button:
  - platform: restart
    name: ${friendly_name} Speakers Restart